export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_ASYN_SUCCESS = 'SIGN_IN_ASYN_SUCCESS';
export const SIGN_IN_ASYN_FAIL = 'SIGN_IN_ASYN_FAIL';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_ASYN_SUCCESS = 'SIGN_UP_ASYN_SUCCESS';
export const SIGN_UP_ASYN_FAIL = 'SIGN_UP_ASYN_FAIL';

export const RESET_STATE = 'RESET_STATE';
export const RESET_STATE_SIGN_IN = 'RESET_STATE_SIGN_IN';

export const LOAD_DATA = 'LOAD_DATA';
export const LOAD_DATA_ASYN_SUCCESS = 'LOAD_DATA_ASYN_SUCCESS';
export const LOAD_DATA_ASYN_FAIL = 'LOAD_DATA_ASYN_FAIL';
export const RESET_STATE_SIGN_UP = 'RESET_STATE_SIGN_UP';

export const SIGN_IN_WITH_FACEBOOK = 'SIGN_IN_WITH_FACEBOOK';

export const SAVE_TODOS = 'SAVE_TODOS';
export const RESET_STATE_SAVE_TODOS = 'RESET_STATE_SAVE_TODOS';
export const SAVE_TODOS_ASYN_SUCCESS = 'SAVE_TODOS_ASYN_SUCCESS';
export const SAVE_TODOS_ASYN_FAIL = 'SAVE_TODOS_ASYN_FAIL';

export const RESET_IS_LOAD = 'RESET_IS_LOAD';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';
export const RESET_IS_SUCCESS_DELETE = 'RESET_IS_SUCCESS_DELETE';

export const EDIT_TODO = 'EDIT_TODO';

